export const url = process.env.NEXT_PUBLIC_API_URL || 'https://api.imovelpericiado.com/v1'

export const endpoint = {
  addresses: '/places/autocomplete/',
  documents: {
    upload: '/documents/upload/',
  },
  payments: {
    process: '/payments/',
    status: '/payments',
  },
  start: '/auth/start/',
  verify: '/auth/verify/',
  refresh: '/auth/refresh/',
  me: '/me/',
  orders: '/orders/',
  reRequest: (orderId: string) => `/orders/${orderId}/re-request/`,
  plans: '/plans/',
  /** PDF do relatório de análise. GET com Bearer retorna application/pdf. Parâmetro: order ID. */
  analysisPdfView: (orderId: string) => `/analysis/pdfview/${orderId}`,
  outreach: {
    registryTemplates: '/admin/outreach/templates/registry/',
    emailTemplates: '/admin/outreach/templates/email-db/',
    whatsappSpecs: '/admin/outreach/templates/whatsapp-db/',
    metaWaPreview: '/admin/outreach/templates/whatsapp-db/meta-preview/',
    metaWaSync: '/admin/outreach/templates/whatsapp-db/sync-from-meta/',
    campaigns: '/admin/outreach/campaigns/',
    campaignsCreate: '/admin/outreach/campaigns/create/',
    campaignsCreateFromRows: '/admin/outreach/campaigns/create-from-rows/',
    campaignAppendRows: (id: string) => `/admin/outreach/campaigns/${id}/append-rows/`,
    campaign: (id: string) => `/admin/outreach/campaigns/${id}/`,
    campaignPreview: (id: string) => `/admin/outreach/campaigns/${id}/preview/`,
    campaignSend: (id: string) => `/admin/outreach/campaigns/${id}/send/`,
    campaignRecipients: (id: string) => `/admin/outreach/campaigns/${id}/recipients/`,
  },
  chat: {
    campaigns: '/admin/chat/campaigns/',
    campaign: (id: string) => `/admin/chat/campaigns/${id}/`,
    conversations: '/admin/chat/conversations/',
    conversation: (id: string) => `/admin/chat/conversations/${id}/`,
    conversationMessages: (id: string) => `/admin/chat/conversations/${id}/messages/`,
    conversationHandoff: (id: string) => `/admin/chat/conversations/${id}/handoff/`,
    conversationToggleAi: (id: string) => `/admin/chat/conversations/${id}/toggle-ai/`,
    conversationReplayAi: (id: string) => `/admin/chat/conversations/${id}/replay-ai/`,
    leads: '/admin/chat/leads/',
    lead: (id: string) => `/admin/chat/leads/${id}/`,
    scheduled: '/admin/chat/scheduled/',
    scheduledCancel: (id: string) => `/admin/chat/scheduled/${id}/cancel/`,
  },
}